/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 * PA5 - AF1 - TIM2_CH1/TIM2_ETR
 * PA6 - AF2 - TIM3_CH1
 */

#include <stdint.h>
#include "stm32f4xx_ll_bus.h"
#include "stm32f4xx_ll_gpio.h"
#include "stm32f4xx_ll_tim.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ever		;;

void tim2_init();
void tim3_ic_init();

volatile uint32_t timestamp = 0;

int main(void)
{
	tim2_init();
	tim3_ic_init();

    /* Loop forever */
	for(ever)
	{
		/* wait until edge is captured */
		while(!LL_TIM_IsActiveFlag_UPDATE(TIM3));

		/* read captured counter value */
		timestamp = LL_TIM_IC_GetCaptureCH1(TIM3);
	}
}

void tim2_init()
{
	/* enable clock for GPIOA */
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);

	/* set pin to output mode */
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_5, LL_GPIO_MODE_ALTERNATE);

	/* set alternate function type */
	LL_GPIO_SetAFPin_0_7(GPIOA, LL_GPIO_PIN_5, LL_GPIO_AF_1);

	/* enable clock access to timer module */
	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_TIM2);

	/* set the pre-scaler */
	LL_TIM_SetPrescaler(TIM2, 1600 - 1);

	/* set output compare mode: toggle */
	LL_TIM_OC_SetMode(TIM2, LL_TIM_CHANNEL_CH1, LL_TIM_OCMODE_TOGGLE);

	/* enable ch1 */
	LL_TIM_CC_EnableChannel(TIM2, LL_TIM_CHANNEL_CH1);

	/* set auto-reload value */
	LL_TIM_SetAutoReload(TIM2, 10000 - 1);

	/* enable channel compare mode */
	LL_TIM_CC_EnableChannel(TIM2, LL_TIM_CHANNEL_CH1);

	/* reset the counter */
	LL_TIM_SetCounter(TIM2, 0);

	/* enable timer module */
	LL_TIM_EnableCounter(TIM2);
}

void tim3_ic_init()
{
	/* enable clock access to timer module */
	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_TIM3);

	/* enable clock for GPIOA */
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);

	/* set pin to output mode */
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_6, LL_GPIO_MODE_ALTERNATE);

	/* set alternate function type */
	LL_GPIO_SetAFPin_0_7(GPIOA, LL_GPIO_PIN_6, LL_GPIO_AF_2);

	/* set the pre-scaler */
	LL_TIM_SetPrescaler(TIM3, 1600 - 1);

	/*  */
	LL_TIM_IC_SetActiveInput(TIM3, LL_TIM_CHANNEL_CH1,
			LL_TIM_ACTIVEINPUT_DIRECTTI);

	/* set polarity */
	LL_TIM_IC_SetPolarity(TIM3, LL_TIM_CHANNEL_CH1, LL_TIM_IC_POLARITY_RISING);

	/* enable channel compare mode */
	LL_TIM_CC_EnableChannel(TIM3, LL_TIM_CHANNEL_CH1);

	/* enable timer module */
	LL_TIM_EnableCounter(TIM3);
}


