/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void task1_handler();
void task2_handler();
void task3_handler();
void task4_handler();

void init_systick_timer(uint32_t tick_hz);

void SysTick_Handler();

// stack memory calculations
#define SIZE_TASK_STACK 		1024U
#define SIZE_SCHEDULER_STACK 	1024U

// see STM32F446RETX_RAM.ld
#define SRAM_START 				0x20000000U
#define SIZE_RAM				(128 * 1024)
#define SRAM_END				(SRAM_START + SIZE_RAM)

#define T1_STACK_START			SRAM_END
#define T2_STACK_START			(SRAM_END - (1 * SIZE_TASK_STACK))
#define T3_STACK_START			(SRAM_END - (2 * SIZE_TASK_STACK))
#define T4_STACK_START			(SRAM_END - (3 * SIZE_TASK_STACK))
#define SCHED_STACK_START		(SRAM_END - (4 * SIZE_TASK_STACK))

#define TICK_HZ 				1000U

#define HSI_CLOCK				16000000U
#define SYSTICK_TIMER_CLOCK		HSI_CLOCK

int main(void)
{
	init_systick_timer(TICK_HZ);
    /* Loop forever */
	for(;;);
}

void task1_handler()
{
	while(1)
	{
		printf("task1\n");
	}
}

void task2_handler()
{
	while(1)
	{
		printf("task2\n");
	}
}

void task3_handler()
{
	while(1)
	{
		printf("task3\n");
	}
}

void task4_handler()
{
	while(1)
	{
		printf("task4\n");
	}
}

void init_systick_timer(uint32_t tick_hz)
{
	// SYST_RVR
	uint32_t *pSRVR = (uint32_t *)0xE000E014;
	// SYST_CSR
	uint32_t *pSCSR = (uint32_t *)0xE000E010;

	uint32_t count_value = (SYSTICK_TIMER_CLOCK/tick_hz) - 1;

	// clear the value of SVR
	*pSRVR &= ~(0x00FFFFFFFF);

	// load the value in to SVR
	*pSRVR |= count_value;

	// rever to Table 4-33 SysTick SYST_CSR register bit assignments
	// settings
	*pSCSR |= (1 << 1); // enable systick exception request
	*pSCSR |= (1 << 2); // indicates the clock source, processor clock source

	// enable systick
	*pSCSR |= (1 << 0); // enable the counter
}

void SysTick_Handler()
{

}
