/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
#if 0
	__asm volatile("LDR R1,=#0x20001000");
	__asm volatile("LDR R2,=#0x20001004");
	__asm volatile("LDR R0,[R1]");
	__asm volatile("LDR R1,[R2]");
	__asm volatile("ADD R0,R0,R1");
	__asm volatile("STR R0,[R2]");
#endif

	int val = 50;
	/**
	 * 		int val = 50;
	 * 	800020a:	2332      	movs	r3, #50	; 0x32
	 *	800020c:	607b      	str	r3, [r7, #4]
	 * 		__asm volatile("MOV R0,%0"::"r"(val));
	 * 	800020e:	687b      	ldr	r3, [r7, #4]
	 * 	8000210:	4618      	mov	r0, r3
	 */
	__asm volatile("MOV R0,%0"::"r"(val));

	int control_reg;
	// read CONTROL register to control_reg
	__asm volatile("MRS %0, CONTROL":"=r"(control_reg)::);

	/**
	 * example 3: copy the content of C variable var1
	 * to var2
	 */
	int var1=10, var2;
	__asm volatile("MOV %0,%1":"=r"(var2):"r"(var1));

	/**
	 * example 4: copy the contents of a pointer into
	 * another variable
	 */
	int p1, *p2;
	p2 = (int*)0x20000008;
	// p1 = *p2
	__asm volatile("LDR %0,[%1]":"=r"(p1):"r"(p2));

    /* Loop forever */
	for(;;);
}
