/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx_ll_bus.h"
#include "stm32f4xx_ll_gpio.h"
#include "stm32f4xx_ll_tim.h"
#include "stm32f4xx_ll_adc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ever		;;

void adc1_init();

uint32_t volatile sensor_value = 0;

int main(void)
{
	adc1_init();

    /* Loop forever */
	for(ever)
	{
		/* start ADC conversion */
		LL_ADC_REG_StartConversionSWStart(ADC1);

		/* wait for conversion to be complete */
		while(!LL_ADC_IsActiveFlag_EOCS(ADC1));

		/* read converted value */
		uint32_t temp = LL_ADC_REG_ReadConversionData32(ADC1);
		sensor_value = (500 * temp) / 1024;
	}
}

void adc1_init()
{
	/* enable clock access to ADC module */
	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_ADC1);

	/* enable clock access to ADC channel port */
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);

	/* set ADC channel pin model to analog */
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_1, LL_GPIO_MODE_ANALOG);

	/* set ADC trigger */
	LL_ADC_REG_SetTriggerSource(ADC1, LL_ADC_REG_TRIG_SOFTWARE);

	/* set sampling sequence */
	LL_ADC_REG_SetSequencerRanks(ADC1, LL_ADC_REG_RANK_1, LL_ADC_CHANNEL_1);

	/* set sequence length */
	LL_ADC_REG_SetSequencerLength(ADC1, LL_ADC_REG_SEQ_SCAN_DISABLE);

	/* enable ADC */
	LL_ADC_Enable(ADC1);
}

