/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 *
 * define: STM32F446xx
 *
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>

#include "uart_dma.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ever			;;

extern uint8_t g_rx_cmplt;
extern uint8_t g_uart_cmplt;
extern uint8_t g_tx_cmplt;

extern char uart_data_buffer[UART_DATA_BUFF_SIZE];
char msg_buff[120] ={'\0'};

int main(void)
{
	uart2_rx_tx_init();
	dma1_init();
	dma1_stream5_uart_rx_config();
	snprintf(msg_buff, sizeof(msg_buff), "initialization complete!\n\r");

	int msg_buff_len = sizeof(msg_buff) / sizeof(msg_buff[0]);

	dma1_stream6_uart_tx_config((uint32_t)msg_buff,msg_buff_len);

    while(!g_tx_cmplt){}

    /* Loop forever */
	for(ever)
	{
		if(g_rx_cmplt)
		{
			snprintf(msg_buff, sizeof(msg_buff), "message received: %s \r\n", uart_data_buffer);
			g_rx_cmplt = 0;
			g_tx_cmplt = 0;
			g_uart_cmplt = 0;
			dma1_stream6_uart_tx_config((uint32_t)msg_buff,msg_buff_len);
		    while(!g_tx_cmplt){}

		}
	}
}
