/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 *
 * The USART2 interface available on PA2 and PA3 of the STM32 microcontroller can be
 * connected to ST-LINK MCU, ST morpho connector, or to ARDUINO® connector.
 *
 * PA2 - USART2_TX - AF7
 * PA3 - USART2_RX - AF7
 */

#include <stdint.h>

#include "stm32f4xx_ll_bus.h"
#include "stm32f4xx_ll_gpio.h"
#include "stm32f4xx_ll_usart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define		ever		;;


void uart2_init();
void uart2_write(uint8_t ch);

int main(void)
{
	uart2_init();

    /* Loop forever */
	for(ever)
	{
		uart2_write('Y');
		for (int i = 0; i < 90000; i++);
	}
}

void uart2_init()
{
	/* enable clock  access for UART GPIO pin */
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);

	/* enable clock access for UART module */
	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_USART2);

	/* set model of UART TX pin to alternate function */
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_2, LL_GPIO_MODE_ALTERNATE);

	/* select UART TX alternate function type */
	LL_GPIO_SetAFPin_0_7(GPIOA, LL_GPIO_PIN_2, LL_GPIO_AF_7);

	/* configure UART protocol parameters */
	LL_USART_Disable(USART2);
	LL_USART_SetTransferDirection (USART2, LL_USART_DIRECTION_TX);
	LL_USART_ConfigCharacter(USART2, LL_USART_DATAWIDTH_8B,
			LL_USART_PARITY_NONE, LL_USART_STOPBITS_1);
	LL_USART_SetBaudRate (USART2, 16000000,
			LL_USART_OVERSAMPLING_16, 115200);
	LL_USART_Enable(USART2);
}

void uart2_write(uint8_t ch)
{
	/* wait for TXE flag is active */
	while(!LL_USART_IsActiveFlag_TXE(USART2));

	LL_USART_TransmitData8(USART2, ch);
}

