/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "stm32f4xx_ll_bus.h"
#include "stm32f4xx_ll_gpio.h"
#include "stm32f4xx_ll_usart.h"
#include "stm32f4xx_ll_adc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ever		;;

void adc1_init();
void uart2_init();
void uart2_write(uint8_t ch);

int __io_putchar(int ch)
{
	uart2_write(ch);
	return ch;
}

uint32_t volatile sensor_value = 0;

int main(void)
{
	uart2_init();
	adc1_init();

    /* Loop forever */
	for(ever)
	{
		/* start ADC conversion */
		LL_ADC_REG_StartConversionSWStart(ADC1);

		/* wait for conversion to be complete */
		while(!LL_ADC_IsActiveFlag_EOCS(ADC1));

		/* read converted value */
		uint32_t temp = LL_ADC_REG_ReadConversionData32(ADC1);
		sensor_value = (500 * temp) / 1024;
		printf("temp data: %d\n\r", (int)sensor_value);
	}
}

void adc1_init()
{
	/* enable clock access to ADC module */
	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_ADC1);

	/* enable clock access to ADC channel port */
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);

	/* set ADC channel pin model to analog */
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_1, LL_GPIO_MODE_ANALOG);

	/* set ADC trigger */
	LL_ADC_REG_SetTriggerSource(ADC1, LL_ADC_REG_TRIG_SOFTWARE);

	/* set sampling sequence */
	LL_ADC_REG_SetSequencerRanks(ADC1, LL_ADC_REG_RANK_1, LL_ADC_CHANNEL_1);

	/* set sequence length */
	LL_ADC_REG_SetSequencerLength(ADC1, LL_ADC_REG_SEQ_SCAN_DISABLE);

	/* enable ADC */
	LL_ADC_Enable(ADC1);
}

void uart2_init()
{
	/* enable clock  access for UART GPIO pin */
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);

	/* enable clock access for UART module */
	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_USART2);

	/* set model of UART TX pin to alternate function */
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_2, LL_GPIO_MODE_ALTERNATE);

	/* select UART TX alternate function type */
	LL_GPIO_SetAFPin_0_7(GPIOA, LL_GPIO_PIN_2, LL_GPIO_AF_7);

	/* configure UART protocol parameters */
	LL_USART_Disable(USART2);
	LL_USART_SetTransferDirection (USART2, LL_USART_DIRECTION_TX);
	LL_USART_ConfigCharacter(USART2, LL_USART_DATAWIDTH_8B,
			LL_USART_PARITY_NONE, LL_USART_STOPBITS_1);
	LL_USART_SetBaudRate (USART2, 16000000,
			LL_USART_OVERSAMPLING_16, 115200);
	LL_USART_Enable(USART2);
}

void uart2_write(uint8_t ch)
{
	/* wait for TXE flag is active */
	while(!LL_USART_IsActiveFlag_TXE(USART2));

	LL_USART_TransmitData8(USART2, ch);
}


