/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * this function executes in THREAD MODE
 * of the processor
 */
void generate_interrupt();
/*
 * this function (ISR) executes in HANDLER MODE of the processor
 */
void RTC_WKUP_IRQHandler();

int main(void)
{
	printf("in thread mode: before interrupt\n");

	generate_interrupt();

	printf("in thread mode: after interrupt\n");

    /* Loop forever */
	for(;;);
}

void generate_interrupt()
{
	uint32_t *pSTIR  = (uint32_t*)0xE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	//enable IRQ3 interrupt
	*pISER0 |= ( 1 << 3);

	//generate an interrupt from software for IRQ3
	*pSTIR = (3 & 0x1FF);
}

void RTC_WKUP_IRQHandler()
{
	printf("in handler mode: ISR\n");
}
