/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "stm32f4xx_ll_bus.h"
#include "stm32f4xx_ll_gpio.h"
#include "stm32f4xx_ll_usart.h"
#include "stm32f4xx_ll_adc.h"
#include "stm32f4xx_ll_exti.h"
#include "stm32f4xx_ll_system.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ever		;;

void adc1_init();
void uart2_init();
void uart2_write(uint8_t ch);
void gpio_interrupt_init();

int __io_putchar(int ch)
{
	uart2_write(ch);
	return ch;
}

uint32_t volatile rotation_value = 0;

int main(void)
{
	gpio_interrupt_init();
	uart2_init();
	adc1_init();

    /* Loop forever */
	for(ever)
	{
		/* start ADC conversion */
//		LL_ADC_REG_StartConversionSWStart(ADC1);
	}
}

void adc1_init()
{
	/* enable clock access to ADC module */
	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_ADC1);

	/* enable clock access to ADC channel port */
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);

	/* set ADC channel pin model to analog */
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_1, LL_GPIO_MODE_ANALOG);

	NVIC_SetPriority(ADC_IRQn, 0);
	NVIC_EnableIRQ(ADC_IRQn);

	/* set ADC clock */
	LL_ADC_SetCommonClock(__LL_ADC_COMMON_INSTANCE(ADC1), LL_ADC_CLOCK_SYNC_PCLK_DIV2);

	/* set the sequencer mode */
	LL_ADC_SetSequencersScanMode(ADC1, LL_ADC_SEQ_SCAN_ENABLE);

	/* set ADC trigger source */
	LL_ADC_REG_SetTriggerSource(ADC1, LL_ADC_REG_TRIG_SOFTWARE);

	/* set continuous mode */
	LL_ADC_REG_SetContinuousMode(ADC1, LL_ADC_REG_CONV_SINGLE);

	/* set sequence length */
	LL_ADC_REG_SetSequencerLength(ADC1, LL_ADC_REG_SEQ_SCAN_DISABLE);

	/* set sampling sequence */
	LL_ADC_REG_SetSequencerRanks(ADC1, LL_ADC_REG_RANK_1, LL_ADC_CHANNEL_1);

	LL_ADC_SetChannelSamplingTime(ADC1, LL_ADC_CHANNEL_1, LL_ADC_SAMPLINGTIME_480CYCLES);

	/* enable end-of-conversion interrupt */
	LL_ADC_EnableIT_EOCS(ADC1);

	/* enable ADC OVR interrupt */
	LL_ADC_EnableIT_OVR(ADC1);

	/* enable ADC */
	LL_ADC_Enable(ADC1);
}

void uart2_init()
{
	/* enable clock  access for UART GPIO pin */
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);

	/* enable clock access for UART module */
	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_USART2);

	/* set model of UART TX pin to alternate function */
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_2, LL_GPIO_MODE_ALTERNATE);

	/* select UART TX alternate function type */
	LL_GPIO_SetAFPin_0_7(GPIOA, LL_GPIO_PIN_2, LL_GPIO_AF_7);

	/* configure UART protocol parameters */
	LL_USART_Disable(USART2);
	LL_USART_SetTransferDirection (USART2, LL_USART_DIRECTION_TX);
	LL_USART_ConfigCharacter(USART2, LL_USART_DATAWIDTH_8B,
			LL_USART_PARITY_NONE, LL_USART_STOPBITS_1);
	LL_USART_SetBaudRate (USART2, 16000000,
			LL_USART_OVERSAMPLING_16, 115200);
	LL_USART_Enable(USART2);
}

void uart2_write(uint8_t ch)
{
	/* wait for TXE flag is active */
	while(!LL_USART_IsActiveFlag_TXE(USART2));

	LL_USART_TransmitData8(USART2, ch);
}

void gpio_interrupt_init()
{
	/* clock GPIOC */
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOC);

	/* set PC13 to input pin - push button */
	LL_GPIO_SetPinMode(GPIOC, LL_GPIO_PIN_13, LL_GPIO_MODE_INPUT);

	/* enable clock access to EXTI module */
	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_SYSCFG);

	/* set EXTI source - PC13 */
	LL_SYSCFG_SetEXTISource(LL_SYSCFG_EXTI_PORTC, LL_SYSCFG_EXTI_LINE13);

	/* enable EXTI line */
	LL_EXTI_EnableIT_0_31(LL_EXTI_LINE_13);

	/* set the trigger */
	LL_EXTI_EnableFallingTrig_0_31(LL_EXTI_LINE_13);

	/* enable NVIC interrupt */
	NVIC_EnableIRQ(EXTI15_10_IRQn);

	/* set the interrupt priority */
	NVIC_SetPriority(EXTI15_10_IRQn, 0);
}

void ADC_IRQHandler()
{
	if (LL_ADC_IsActiveFlag_OVR(ADC1) != 0)
	{
		printf("ADC overrun \n\r");
	}
	else
	{
		/* clear flag */
		LL_ADC_ClearFlag_EOCS(ADC1);

		/* read converted value */
		rotation_value = LL_ADC_REG_ReadConversionData32(ADC1);
		printf("rotation_value: %d\n\r", (int)rotation_value);
	}
}

void EXTI15_10_IRQHandler()
{
	if (LL_EXTI_IsActiveFlag_0_31(LL_EXTI_LINE_13) != RESET)
	{
		/* start ADC conversion */
		LL_ADC_REG_StartConversionSWStart(ADC1);

		LL_EXTI_ClearFlag_0_31(LL_EXTI_LINE_13);
	}
}
